"""API v1 router."""

from fastapi import APIRouter

from src.api.v1.routers import (
    auth,
    bookings,
    clinics,
    config,
    doctors,
    patients,
    payments,
    schedule,
    services,
    stickers,
    csv_sync,
    reports,
    admin_services,
    admin_schedule,
    admin_doctor_schedule,
    admin_prepayment,
    admin_waitlist,
    admin_recall,
    admin_marketing,
    admin_reports,
    admin_reports_aggregate,
    admin_chat,
    admin_channel_configs,
    admin_admins,
    admin_agreement,
    admin_auth,
    admin_client_reference,
    admin_clinics_summary,
    admin_discounts,
    admin_integrations,
    admin_owner_settings,
    admin_notification_policy,
    admin_attention_feed,
    admin_ai_reports,
    admin_patient_ai,
    admin_ai_settings,
    admin_ai_status,
    admin_ai_tasks_settings,
    admin_public_doctor_profiles,
    public_services,
    patient_notification_settings,
    public_marketing,
    public_doctor_profiles,
    patient_chat,
    admin_omni_chat,
    admin_omni_chat_closure_tags,
    integrations_gateway,
    owner_omni_channels,
    owner_omni_ai_settings,
    owner_omni_audit,
    admin_payment_gateway,
    admin_finance,
    admin_payroll,
    admin_inventory,
    admin_crm,
    admin_tasks,
    admin_task_boards,
    admin_task_streams,
    admin_task_tags,
    admin_staff_collab,
    admin_staff_announcement_policy,
    admin_loyalty,
    patient_loyalty,
    admin_forms,
    patient_forms,
    admin_marketing_attribution,
    admin_search,
    ai_agent,
    admin_retention,
    admin_vault,
    admin_ui_events,
    admin_omni_tools,
    admin_rbac_management,
    admin_staff_directory,
    admin_staff_profile,
    admin_patient_medical,
    admin_lead_logs,
    admin_leads_log_routing,
)

# Create main API router
api_router = APIRouter()

api_router.include_router(auth.router)
api_router.include_router(config.router)
api_router.include_router(stickers.router)
api_router.include_router(clinics.router)
api_router.include_router(doctors.router)
api_router.include_router(services.router)
api_router.include_router(admin_services.router)
api_router.include_router(admin_schedule.router)
api_router.include_router(admin_doctor_schedule.router)
api_router.include_router(admin_prepayment.router)
api_router.include_router(admin_waitlist.router)
api_router.include_router(admin_recall.router)
api_router.include_router(admin_marketing.router)
api_router.include_router(admin_reports.router)
api_router.include_router(admin_reports_aggregate.router)
api_router.include_router(admin_marketing_attribution.router)
api_router.include_router(admin_chat.router)
api_router.include_router(admin_channel_configs.router)
api_router.include_router(admin_admins.router)
api_router.include_router(admin_staff_directory.router)
api_router.include_router(admin_staff_profile.router)
api_router.include_router(admin_patient_medical.router)
api_router.include_router(admin_agreement.router)
api_router.include_router(admin_auth.router)
api_router.include_router(admin_client_reference.router)
api_router.include_router(admin_clinics_summary.router)
api_router.include_router(admin_discounts.router)
api_router.include_router(admin_integrations.router)
api_router.include_router(admin_owner_settings.router)
api_router.include_router(admin_notification_policy.router)
api_router.include_router(admin_attention_feed.router)
api_router.include_router(admin_patient_ai.router)
api_router.include_router(admin_ai_settings.router)
api_router.include_router(admin_ai_reports.router)
api_router.include_router(admin_ai_status.router)
api_router.include_router(admin_ai_tasks_settings.router)
api_router.include_router(admin_public_doctor_profiles.router)
api_router.include_router(admin_payment_gateway.router)
api_router.include_router(admin_finance.router)
api_router.include_router(admin_payroll.router)
api_router.include_router(admin_inventory.router)
api_router.include_router(admin_crm.router)
api_router.include_router(admin_tasks.router)
api_router.include_router(admin_task_boards.router)
api_router.include_router(admin_task_streams.router)
api_router.include_router(admin_task_tags.router)
api_router.include_router(admin_staff_collab.router)
api_router.include_router(admin_staff_announcement_policy.router)
api_router.include_router(patient_chat.router)
api_router.include_router(patient_notification_settings.router)
api_router.include_router(public_services.router)
api_router.include_router(public_marketing.router)
api_router.include_router(public_doctor_profiles.router)
api_router.include_router(patients.router)
api_router.include_router(schedule.router)
api_router.include_router(bookings.router)
api_router.include_router(payments.router)
api_router.include_router(csv_sync.router)
api_router.include_router(reports.router)
api_router.include_router(admin_omni_chat.router)
api_router.include_router(admin_omni_chat_closure_tags.router)
api_router.include_router(integrations_gateway.router)
api_router.include_router(owner_omni_channels.router)
api_router.include_router(owner_omni_ai_settings.router)
api_router.include_router(owner_omni_audit.router)
api_router.include_router(admin_loyalty.router)
api_router.include_router(patient_loyalty.router)
api_router.include_router(admin_forms.router)
api_router.include_router(patient_forms.router)
api_router.include_router(admin_search.router)
api_router.include_router(ai_agent.router)
api_router.include_router(admin_retention.router)
api_router.include_router(admin_vault.router)
api_router.include_router(admin_ui_events.router)
api_router.include_router(admin_omni_tools.router)
api_router.include_router(admin_rbac_management.router)
api_router.include_router(admin_lead_logs.router)
api_router.include_router(admin_leads_log_routing.router)