"""DTOs for omni chat presence/leases."""

from __future__ import annotations

from datetime import datetime
from uuid import UUID

from pydantic import BaseModel, Field


class OmniChatPresenceRequest(BaseModel):
    client_event_id: UUID = Field(..., description="Idempotency key generated by client")
    tab_id: str = Field(..., min_length=6, max_length=64)
    event: str = Field(..., pattern="^(OPEN|HEARTBEAT|CLOSE)$")


class OmniChatLeaseDto(BaseModel):
    chat_id: UUID
    admin_id: UUID
    tab_id: str
    expires_at: datetime
    last_heartbeat_at: datetime


class OmniChatPresenceResponse(BaseModel):
    lease: OmniChatLeaseDto | None = None
    claimed: bool = False
    assignee_admin_id: UUID | None = None

